### ISSUE TITLE
Script to train starcoder

### ISSUE THREAD

**Issue by edward-io** [bigcode-project/Megatron-LM#49]
It would be very useful to have a script to reproduce and/or finetune StarCoder, similar to the [example script for santacoder](https://github.com/bigcode-project/Megatron-LM/blob/1a7d54bc3f897d068eb78c5b0874d4d69c9af5ea/examples/pretrain_gpt_1B_santacoder.sh).

HuggingFace's trainer doesn't have the ability to do tensor/model parallel, which makes it difficult to fit the model on 1 8-GPU node, so this code would help users fine-tune models.

**Comment by loubnabnl** [comment]
The training script is available at: https://github.com/bigcode-project/Megatron-LM/blob/multi-query-attention/examples/pretrain_bigcode_model.slurm
You can also use HuggingFace Trainer with DeepSpeed, documentation available [here](https://huggingface.co/docs/transformers/main_classes/deepspeed) or Peft, we provide some examples in [StarCoder repo](https://github.com/bigcode-project/starcoder)

**Comment by edward-io** [comment]
Thank you! For those looking for weights, they're located here: https://huggingface.co/bigcode/starcoder-megatron
