### ISSUE TITLE
List of things to be (potentially) ported from Megatron-DeepSpeed

### ISSUE THREAD

**Issue by mayank31398** [bigcode-project/Megatron-LM#6]
- [x] [AliBi embeddings](https://github.com/bigcode-project/Megatron-LM/pull/5)
- [ ] Checkpoint reshaping
- [ ] Universal checkpoints

Feel free to add more things if required.

**Comment by mintsugaEHEH** [comment]
Hello. I try to reshape a fine-tuned checkpoint of starcoder(https://huggingface.co/bigcode/starcoder-megatron/tree/main)  from TP=4,PP=4 to TP=8,PP=1 using tools/checkpoint_util.py, but I encountered a memory OOM issue.
The machine I used has a memory of 512GB which is capable of loading the whole model. Any solution to solve this issue?

**Comment by mayank31398** [comment]
closing since its too old
