### ISSUE TITLE
how to convert huggingface?

### ISSUE THREAD

**Issue by cdj0311** [bigcode-project/Megatron-LM#63]
hi, 
The megatron format how to convert huggingface for inference?

**Comment by seopbo** [comment]
Did you find it? @cdj0311

**Comment by cdj0311** [comment]
> Did you find it? @cdj0311

https://github.com/bigcode-project/transformers/blob/main/src/transformers/models/megatron_gpt_bigcode/convert_megatron_gpt_bigcode_checkpoint.py
