### ISSUE TITLE
Train Python model with FIM

### ISSUE THREAD

**Issue by harm-devries** [bigcode-project/Megatron-LM#8]
As discussed today, let's train a 350M model with the following hyper parameters:
- FIM rate 0.5
- SPM vs PSM: 0.5
- ALiBi encodings
- Multi-Head Attention  

Let's see how it compares against previously trained models.

**Comment by lvwerra** [comment]
@RaymondLi0 was this the run with the results you showed last week? Would you mind adding them here?

**Comment by RaymondLi0** [comment]
A 350M model was trained on https://huggingface.co/datasets/bigcode/permissive-python-dedup-decontaminate with:
- fim_rate=0.5
- fim_spm_rate=0.5
- absolute positional encodings
- multi-head attention

There is a slight degradation at 300k steps (around 2% pass-at-10 and pass-at-100).
At 150k steps, which matches the amount of training tokens used in the FIM paper, there is no degradation.

![Figure 12 (2)](https://user-images.githubusercontent.com/11444023/203109882-6016cb3c-5110-4414-8876-aeb9d13c7b0f.png)
![Figure 11 (2)](https://user-images.githubusercontent.com/11444023/203109886-8f769a61-d40d-4b66-8f2f-3ce0eac11d20.png)
![Figure 6 (1)](https://user-images.githubusercontent.com/11444023/203109891-4636ecfb-52b5-48ef-bd07-b2d794dc5105.png)

**Comment by sepilqi** [comment]
@RaymondLi0 this link is not available https://huggingface.co/datasets/bigcode/permissive-python-dedup-decontaminate

**Comment by lvwerra** [comment]
This is a private dev dataset. You can use the Python subset of https://huggingface.co/datasets/bigcode/the-stack-dedup instead.
